CheckUser = 'CheckUser'
Menu = 'Menu'
Help = 'Help'

Methods = 'Methods'
Diary = 'Diary'
SearchAdmin = 'SearchAdmin'
UserLibrary = 'UserLibrary'
UserUpload = 'UserUpload'
CreateFile = 'CreateFile'
DiaryUpload = 'DiaryUpload'
DocSave = 'DocSave'
EditInfo = 'EditInfo'
EraseDoc = 'EraseDoc'
ShowDiary = 'ShowDiary'